apiVersion: v1
kind: Service
metadata:
  name: testangular-app-service
spec:
  selector:
    app: testangular-app-service
  ports:
  - protocol: "TCP"
    port: 8181
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testangular-app-service
spec:
  selector:
    matchLabels:
      app: testangular-app-service
  replicas: 5
  template:
    metadata:
      labels:
        app: testangular-app-service
    spec:
      containers:
      - name: testangular-app-service
        image: chan29/testangular:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80